onEvent('fluid.registry', event => {
    event.create('molten_hardened_gold')
    .displayName('§6Molten Hardened Gold')
    .thickTexture(0xF7B30E)
    .bucketColor(0xF7B30E)
    .luminosity(100)
    .viscosity(100)
    .density(100)
    .temperature(950)

    event.create('molten_hardened_manyullyn')
    .displayName('§5Molten Hardened Manyullyn')
    .thickTexture(0x5E3592)
    .bucketColor(0x5E3592)
    .luminosity(100)
    .viscosity(100)
    .density(100)
    .temperature(2500)
})
